let letra;
letra='a';
console.log('letra',letra);

const palavra='olá';
console.log('palavra',palavra);
let v1=2;
let v2=3;
console.log('v3',v1*v2);
console.log('====');
let l1='a';
let l2='b';
console.log('l3',l1+l2);
console.log(`l3 ${l1+l2}`);
console.log('====');
let v3=null;
console.log(v3);
console.log('====');
const a=[1,2];
const b=a;
console.log(a,b);
b.push(3);
console.log(a,b);
console.log('====');
let a2=1;
let b2=a2;
console.log(a2,b2);
b2=2;
console.log(a2,b2);
console.log('====');
console.log(typeof(true));
console.log(typeof(1));
console.log(typeof(1.2));
console.log(typeof('1.2'));
console.log(typeof(['1.2','a']));
console.log(typeof({'a':'1.2','b':'a'}));
